tasks:
  - init: |
      cp .env.example .env &&
      sed -i -r "s#^(NEXTAUTH_URL=).*#\1 $(gp url 3000)#" .env && 
      sed -i -r "s#^(NEXT_PUBLIC_WEBAPP_URL=).*#\1 $(gp url 3000)#" .env && 
      sed -i -r "s#^(NEXT_PUBLIC_MARKETING_URL=).*#\1 $(gp url 3001)#" .env && 
      npm run dx &&
    command: npm run dev
ports:
  - port: 3000
    visibility: public
    onOpen: open-browser

  - port: 3001
    visibility: public
    onOpen: open-browser

  - port: 9000
    visibility: public
    onOpen: ignore

  - port: 1100
    visibility: public
    onOpen: ignore


github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - DavidAnson.vscode-markdownlint
    - yzhang.markdown-all-in-one
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - ban.spellright
    - Prisma.prisma