tasks:
  - init: |
      cp .env.example .env &&
      sed -i -r "s#^(NEXTAUTH_URL=).*#\1 $(gp url 3000)#" .env && 
      sed -i -r "s#^(NEXT_PUBLIC_WEBAPP_URL=).*#\1 $(gp url 3000)#" .env && 
      sed -i -r "s#^(NEXT_PUBLIC_MARKETING_URL=).*#\1 $(gp url 3001)#" .env && 
       sed -i -r "s#^(NEXT_PRIVATE_DATABASE_URL=).*#\1\"postgres://documenso:password@database:54320/documenso\"#" .env &&
      sed -i -r "s#^(NEXT_PRIVATE_DIRECT_DATABASE_URL=).*#\1\"postgres://documenso:password@database:54320/documenso\"#" .env &&
      cp .env packages/prisma/.env &&
      npm run dx
    command: npm run dev
ports:
  - port: 3000
    visibility: public
    onOpen: open-browser

  - port: 3001
    visibility: public
    onOpen: open-browser

  - port: 9000
    visibility: public
    onOpen: ignore

  - port: 2025
    visibility: public
    onOpen: ignore
  
  - port: 1100
    visibility: public
    onOpen: ignore
  - port: 54320
    visibility: public
    onOpen: ignore
  
github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - DavidAnson.vscode-markdownlint
    - yzhang.markdown-all-in-one
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - ban.spellright
    - Prisma.prisma
   